// <auto-generated />
using DestritosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DestritosAPI.Migrations
{
    [DbContext(typeof(DestritosAPIContext))]
    partial class DestritosAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DestritosAPI.Models.Conselho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Conselhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistritoId = 1,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 2,
                            DistritoId = 1,
                            Name = "Amadora"
                        },
                        new
                        {
                            Id = 3,
                            DistritoId = 1,
                            Name = "Cascais"
                        },
                        new
                        {
                            Id = 4,
                            DistritoId = 1,
                            Name = "Odivelas"
                        },
                        new
                        {
                            Id = 5,
                            DistritoId = 1,
                            Name = "Sintra"
                        },
                        new
                        {
                            Id = 6,
                            DistritoId = 2,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 7,
                            DistritoId = 2,
                            Name = "Gondomar"
                        },
                        new
                        {
                            Id = 8,
                            DistritoId = 2,
                            Name = "Maia"
                        },
                        new
                        {
                            Id = 9,
                            DistritoId = 2,
                            Name = "Lousada"
                        },
                        new
                        {
                            Id = 10,
                            DistritoId = 2,
                            Name = "Trofa"
                        },
                        new
                        {
                            Id = 11,
                            DistritoId = 3,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 12,
                            DistritoId = 3,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 13,
                            DistritoId = 3,
                            Name = "Moura"
                        },
                        new
                        {
                            Id = 14,
                            DistritoId = 3,
                            Name = "Alvito"
                        },
                        new
                        {
                            Id = 15,
                            DistritoId = 3,
                            Name = "Ourique"
                        },
                        new
                        {
                            Id = 16,
                            DistritoId = 4,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 17,
                            DistritoId = 4,
                            Name = "Barcelos"
                        },
                        new
                        {
                            Id = 18,
                            DistritoId = 4,
                            Name = "Amares"
                        },
                        new
                        {
                            Id = 19,
                            DistritoId = 4,
                            Name = "Guimarães"
                        },
                        new
                        {
                            Id = 20,
                            DistritoId = 4,
                            Name = "Visela"
                        },
                        new
                        {
                            Id = 21,
                            DistritoId = 5,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 22,
                            DistritoId = 5,
                            Name = "Góis"
                        },
                        new
                        {
                            Id = 23,
                            DistritoId = 5,
                            Name = "Mira"
                        },
                        new
                        {
                            Id = 24,
                            DistritoId = 5,
                            Name = "Penela"
                        },
                        new
                        {
                            Id = 25,
                            DistritoId = 5,
                            Name = "Soure"
                        });
                });

            modelBuilder.Entity("DestritosAPI.Models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coimbra"
                        });
                });

            modelBuilder.Entity("DestritosAPI.Models.Freguesia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConselhoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConselhoId");

                    b.ToTable("Freguesias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConselhoId = 1,
                            Name = "Areeiro"
                        },
                        new
                        {
                            Id = 2,
                            ConselhoId = 1,
                            Name = "Beato"
                        },
                        new
                        {
                            Id = 3,
                            ConselhoId = 1,
                            Name = "Campolide"
                        },
                        new
                        {
                            Id = 4,
                            ConselhoId = 1,
                            Name = "Lumiar"
                        },
                        new
                        {
                            Id = 5,
                            ConselhoId = 1,
                            Name = "Olivais"
                        },
                        new
                        {
                            Id = 6,
                            ConselhoId = 2,
                            Name = "Alfragide"
                        },
                        new
                        {
                            Id = 7,
                            ConselhoId = 2,
                            Name = "Encosta do sol"
                        },
                        new
                        {
                            Id = 8,
                            ConselhoId = 2,
                            Name = "Mina de Água"
                        },
                        new
                        {
                            Id = 9,
                            ConselhoId = 2,
                            Name = "Venteira"
                        },
                        new
                        {
                            Id = 10,
                            ConselhoId = 2,
                            Name = "Águas livres"
                        },
                        new
                        {
                            Id = 11,
                            ConselhoId = 3,
                            Name = "Cascais e Estoril"
                        },
                        new
                        {
                            Id = 12,
                            ConselhoId = 3,
                            Name = "Carcavelos e Parede"
                        },
                        new
                        {
                            Id = 13,
                            ConselhoId = 3,
                            Name = "Alcabideche"
                        },
                        new
                        {
                            Id = 14,
                            ConselhoId = 3,
                            Name = "São Domingos de Rana"
                        },
                        new
                        {
                            Id = 15,
                            ConselhoId = 4,
                            Name = "Odivelas"
                        },
                        new
                        {
                            Id = 16,
                            ConselhoId = 4,
                            Name = "Pontinha e Famões"
                        },
                        new
                        {
                            Id = 17,
                            ConselhoId = 4,
                            Name = "Ramada e Caneças"
                        },
                        new
                        {
                            Id = 18,
                            ConselhoId = 5,
                            Name = "Sintra"
                        },
                        new
                        {
                            Id = 19,
                            ConselhoId = 5,
                            Name = "Casal de Cambra"
                        },
                        new
                        {
                            Id = 20,
                            ConselhoId = 5,
                            Name = "Queluz e Belas"
                        },
                        new
                        {
                            Id = 21,
                            ConselhoId = 5,
                            Name = "Rio de Mouro"
                        },
                        new
                        {
                            Id = 22,
                            ConselhoId = 6,
                            Name = "Bonfim"
                        },
                        new
                        {
                            Id = 23,
                            ConselhoId = 6,
                            Name = "Campanhã"
                        },
                        new
                        {
                            Id = 24,
                            ConselhoId = 6,
                            Name = "Paranhos"
                        },
                        new
                        {
                            Id = 25,
                            ConselhoId = 6,
                            Name = "Ramalde"
                        },
                        new
                        {
                            Id = 26,
                            ConselhoId = 7,
                            Name = "Gondomar"
                        },
                        new
                        {
                            Id = 27,
                            ConselhoId = 7,
                            Name = "Lomba"
                        },
                        new
                        {
                            Id = 28,
                            ConselhoId = 7,
                            Name = "Melres e Medas"
                        },
                        new
                        {
                            Id = 29,
                            ConselhoId = 7,
                            Name = "Rio Tinto"
                        },
                        new
                        {
                            Id = 30,
                            ConselhoId = 8,
                            Name = "Moreira"
                        },
                        new
                        {
                            Id = 31,
                            ConselhoId = 8,
                            Name = "Folgosa"
                        },
                        new
                        {
                            Id = 32,
                            ConselhoId = 8,
                            Name = "Pedrouços"
                        },
                        new
                        {
                            Id = 33,
                            ConselhoId = 8,
                            Name = "São Pedro Fins"
                        },
                        new
                        {
                            Id = 34,
                            ConselhoId = 8,
                            Name = "Vila Nova de Telha"
                        },
                        new
                        {
                            Id = 35,
                            ConselhoId = 9,
                            Name = "Aveleda"
                        },
                        new
                        {
                            Id = 36,
                            ConselhoId = 9,
                            Name = "Lodares"
                        },
                        new
                        {
                            Id = 37,
                            ConselhoId = 9,
                            Name = "Macieira"
                        },
                        new
                        {
                            Id = 38,
                            ConselhoId = 9,
                            Name = "Meinedo"
                        },
                        new
                        {
                            Id = 39,
                            ConselhoId = 9,
                            Name = "Sousela"
                        },
                        new
                        {
                            Id = 40,
                            ConselhoId = 10,
                            Name = "Bougado"
                        },
                        new
                        {
                            Id = 41,
                            ConselhoId = 10,
                            Name = "Covelas"
                        },
                        new
                        {
                            Id = 42,
                            ConselhoId = 10,
                            Name = "Muro"
                        },
                        new
                        {
                            Id = 43,
                            ConselhoId = 10,
                            Name = "Coronado"
                        },
                        new
                        {
                            Id = 44,
                            ConselhoId = 11,
                            Name = "Beja"
                        },
                        new
                        {
                            Id = 45,
                            ConselhoId = 11,
                            Name = "Baleizão"
                        },
                        new
                        {
                            Id = 46,
                            ConselhoId = 12,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 47,
                            ConselhoId = 13,
                            Name = "Moura"
                        },
                        new
                        {
                            Id = 48,
                            ConselhoId = 14,
                            Name = "Alvito"
                        },
                        new
                        {
                            Id = 49,
                            ConselhoId = 15,
                            Name = "Ourique"
                        },
                        new
                        {
                            Id = 50,
                            ConselhoId = 15,
                            Name = "Garxão e Santa Luzia"
                        },
                        new
                        {
                            Id = 51,
                            ConselhoId = 15,
                            Name = "Santana da Serra"
                        },
                        new
                        {
                            Id = 52,
                            ConselhoId = 16,
                            Name = "Braga"
                        },
                        new
                        {
                            Id = 53,
                            ConselhoId = 16,
                            Name = "Adaúfe"
                        },
                        new
                        {
                            Id = 54,
                            ConselhoId = 16,
                            Name = "Espinho"
                        },
                        new
                        {
                            Id = 55,
                            ConselhoId = 16,
                            Name = "Lamas"
                        },
                        new
                        {
                            Id = 56,
                            ConselhoId = 16,
                            Name = "Merelim"
                        },
                        new
                        {
                            Id = 57,
                            ConselhoId = 17,
                            Name = "Barcelos"
                        },
                        new
                        {
                            Id = 58,
                            ConselhoId = 17,
                            Name = "Aborim"
                        },
                        new
                        {
                            Id = 59,
                            ConselhoId = 17,
                            Name = "Areias"
                        },
                        new
                        {
                            Id = 60,
                            ConselhoId = 17,
                            Name = "Cristelo"
                        },
                        new
                        {
                            Id = 61,
                            ConselhoId = 17,
                            Name = "Silva"
                        },
                        new
                        {
                            Id = 62,
                            ConselhoId = 18,
                            Name = "Amares e Figueiredo"
                        },
                        new
                        {
                            Id = 63,
                            ConselhoId = 18,
                            Name = "Barreiros"
                        },
                        new
                        {
                            Id = 64,
                            ConselhoId = 18,
                            Name = "Bico"
                        },
                        new
                        {
                            Id = 65,
                            ConselhoId = 18,
                            Name = "Caires"
                        },
                        new
                        {
                            Id = 66,
                            ConselhoId = 18,
                            Name = "Fiscal"
                        },
                        new
                        {
                            Id = 67,
                            ConselhoId = 18,
                            Name = "Lago"
                        },
                        new
                        {
                            Id = 68,
                            ConselhoId = 19,
                            Name = "Aldão"
                        },
                        new
                        {
                            Id = 69,
                            ConselhoId = 19,
                            Name = "Barco"
                        },
                        new
                        {
                            Id = 70,
                            ConselhoId = 19,
                            Name = "Brito"
                        },
                        new
                        {
                            Id = 71,
                            ConselhoId = 19,
                            Name = "Caldelas"
                        },
                        new
                        {
                            Id = 72,
                            ConselhoId = 19,
                            Name = "Costa"
                        },
                        new
                        {
                            Id = 73,
                            ConselhoId = 19,
                            Name = "Pinheiro"
                        },
                        new
                        {
                            Id = 74,
                            ConselhoId = 19,
                            Name = "Ponte"
                        },
                        new
                        {
                            Id = 75,
                            ConselhoId = 20,
                            Name = "Caldas Da Visela"
                        },
                        new
                        {
                            Id = 76,
                            ConselhoId = 20,
                            Name = "Infias"
                        },
                        new
                        {
                            Id = 77,
                            ConselhoId = 21,
                            Name = "Coimbra"
                        },
                        new
                        {
                            Id = 78,
                            ConselhoId = 21,
                            Name = "Ceira"
                        },
                        new
                        {
                            Id = 79,
                            ConselhoId = 21,
                            Name = "São Silvestre"
                        },
                        new
                        {
                            Id = 80,
                            ConselhoId = 21,
                            Name = "Santa Clara e Castelo"
                        },
                        new
                        {
                            Id = 81,
                            ConselhoId = 21,
                            Name = "Torres do Mondego"
                        },
                        new
                        {
                            Id = 82,
                            ConselhoId = 22,
                            Name = "Góis"
                        },
                        new
                        {
                            Id = 83,
                            ConselhoId = 22,
                            Name = "Cadafaz e Colmeal"
                        },
                        new
                        {
                            Id = 84,
                            ConselhoId = 23,
                            Name = "Mira"
                        },
                        new
                        {
                            Id = 85,
                            ConselhoId = 23,
                            Name = "Carapelhos"
                        },
                        new
                        {
                            Id = 86,
                            ConselhoId = 23,
                            Name = "Praia de Mira"
                        },
                        new
                        {
                            Id = 87,
                            ConselhoId = 23,
                            Name = "Seixo"
                        },
                        new
                        {
                            Id = 88,
                            ConselhoId = 24,
                            Name = "Cumeeira"
                        },
                        new
                        {
                            Id = 89,
                            ConselhoId = 24,
                            Name = "Espinhal"
                        },
                        new
                        {
                            Id = 90,
                            ConselhoId = 24,
                            Name = "Podentes"
                        },
                        new
                        {
                            Id = 91,
                            ConselhoId = 25,
                            Name = "Soure"
                        },
                        new
                        {
                            Id = 92,
                            ConselhoId = 25,
                            Name = "Alfarelos"
                        },
                        new
                        {
                            Id = 93,
                            ConselhoId = 25,
                            Name = "Granja do Ulmeiro"
                        },
                        new
                        {
                            Id = 94,
                            ConselhoId = 25,
                            Name = "Samuel"
                        },
                        new
                        {
                            Id = 95,
                            ConselhoId = 25,
                            Name = "Tapéus"
                        });
                });

            modelBuilder.Entity("DestritosAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConselhoId")
                        .HasColumnType("int");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<int>("FreguesiaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConselhoId");

                    b.HasIndex("DistritoId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConselhoId = 2,
                            DistritoId = 1,
                            FreguesiaId = 3,
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 2,
                            ConselhoId = 11,
                            DistritoId = 3,
                            FreguesiaId = 45,
                            Name = "Joana"
                        },
                        new
                        {
                            Id = 3,
                            ConselhoId = 19,
                            DistritoId = 4,
                            FreguesiaId = 70,
                            Name = "Miguel"
                        });
                });

            modelBuilder.Entity("DestritosAPI.Models.Conselho", b =>
                {
                    b.HasOne("DestritosAPI.Models.Distrito", "Distrito")
                        .WithMany("Conselhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DestritosAPI.Models.Freguesia", b =>
                {
                    b.HasOne("DestritosAPI.Models.Conselho", "Conselho")
                        .WithMany("Freguesias")
                        .HasForeignKey("ConselhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DestritosAPI.Models.Pessoa", b =>
                {
                    b.HasOne("DestritosAPI.Models.Conselho", "Conselho")
                        .WithMany()
                        .HasForeignKey("ConselhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DestritosAPI.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DestritosAPI.Models.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
