// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Players_registration.Data;

namespace Players_registration.Migrations
{
    [DbContext(typeof(Players_registrationContext))]
    [Migration("20201007160111_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Players_registration.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Champ",
                            Password = "1234",
                            Points = 500,
                            Rating = 9,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bull",
                            Password = "5678",
                            Points = 300,
                            Rating = 6,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nubb",
                            Password = "4321",
                            Points = 10,
                            Rating = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dumb",
                            Password = "8765",
                            Points = 50,
                            Rating = 2,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("Players_registration.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxPlayersNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPlayersNumber = 2,
                            Name = "Bulls"
                        },
                        new
                        {
                            Id = 2,
                            MaxPlayersNumber = 2,
                            Name = "Eagles"
                        });
                });

            modelBuilder.Entity("Players_registration.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Tournament");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Inferno",
                            Rating = 10,
                            TeamId = 1,
                            Type = "Deathmatch",
                            Votes = 35
                        },
                        new
                        {
                            Id = 2,
                            Name = "Office",
                            Rating = 6,
                            TeamId = 2,
                            Type = "CaptureFlag",
                            Votes = 15
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dust",
                            Rating = 8,
                            TeamId = 2,
                            Type = "Deathmatch",
                            Votes = 25
                        });
                });

            modelBuilder.Entity("Players_registration.Models.Player", b =>
                {
                    b.HasOne("Players_registration.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Players_registration.Models.Tournament", b =>
                {
                    b.HasOne("Players_registration.Models.Team", "Team")
                        .WithMany("Tournaments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
